### ISSUE TITLE
検索がうまく行かない

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/euslisp-docs#1]
https://readthedocs.org//search/?q=%E3%83%AD%E3%83%9C%E3%83%83%E3%83%88&check_keywords=yes&area=default&project=euslisp-docs&version=latest&type=file

**Comment by k-okada** [comment]
なんででしょう？

## 

◉ Kei Okada

**Comment by wkentaro** [comment]
mkdocsだと何か設定が必要なのかもですね。

**Comment by wkentaro** [comment]
パット見ではそのパラメータは見つけられませんが。
http://www.mkdocs.org/user-guide/configuration/

**Comment by wkentaro** [comment]
themeがspacelabだからかもですね。
https://github.com/jsk-ros-pkg/euslisp-docs/blob/master/mkdocs.yml

mkdocsやreadthedocsに変えて試してみるとうまくいくかもしれません。

2015年9月2日水曜日、Kentaro Wada<www.kentaro.wada@gmail.com
<javascript:_e(%7B%7D,'cvml','www.kentaro.wada@gmail.com');>>さんは書きました:

> client search は0.13からサポートされているとここには書いてあります。
> http://www.mkdocs.org/user-guide/styling-your-docs/#custom-themes
> 
> 2015年9月1日火曜日、Kei Okadanotifications@github.comさんは書きました:
> 
> > なんででしょう？
> > 
> > ## 
> > 
> > ◉ Kei Okada
> > 
> > On Tue, Sep 1, 2015 at 8:17 PM, Kentaro Wada notifications@github.com
> > wrote:
> > 
> > > https://readthedocs.org//search/?q=%E3%83%AD%E3%83%9C%E3%83%83%E3%83%88&check_keywords=yes&area=default&project=euslisp-docs&version=latest&type=file
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/jsk-ros-pkg/euslisp-docs/issues/1.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jsk-ros-pkg/euslisp-docs/issues/1#issuecomment-136743071
> > .
> 
> ## 
> 
> 和田 健太郎 / Kentaro Wada
> http://wkentaro.com http://www.wkentaro.com

## 

和田 健太郎 / Kentaro Wada
http://wkentaro.com http://www.wkentaro.com

**Comment by wkentaro** [comment]
client search は0.13からサポートされているとここには書いてあります。
http://www.mkdocs.org/user-guide/styling-your-docs/#custom-themes

2015年9月1日火曜日、Kei Okadanotifications@github.comさんは書きました:

> なんででしょう？
> 
> ## 
> 
> ◉ Kei Okada
> 
> On Tue, Sep 1, 2015 at 8:17 PM, Kentaro Wada <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > https://readthedocs.org//search/?q=%E3%83%AD%E3%83%9C%E3%83%83%E3%83%88&check_keywords=yes&area=default&project=euslisp-docs&version=latest&type=file
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jsk-ros-pkg/euslisp-docs/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jsk-ros-pkg/euslisp-docs/issues/1#issuecomment-136743071
> .

## 

和田 健太郎 / Kentaro Wada
http://wkentaro.com http://www.wkentaro.com

**Comment by wkentaro** [comment]
Not yet.
https://groups.google.com/forum/#!topic/mkdocs/IpvPj4t8zhg
